### ISSUE TITLE
Governance COC: Violence and Threats of Violence

### ISSUE THREAD

**Issue by LGUG2Z** [NixOS/foundation#149]
Taken from the COC: https://github.com/NixOS/foundation/blob/master/governance/zulip/coc.md#violence-and-threats-of-violence

> Violence and threats of violence are not acceptable - online or offline. This includes incitement of violence toward any individual, including encouraging a person to commit self-harm.

Shea Levy made a post about being suspended temporarily from Governance discussions on Zulip: https://twitter.com/shlevy/status/1788192270434386079

> I have been suspended from the NixOS governance Zulip. I will try later today to share my thoughts on what happened and why I think it completely undermines the stated intent of the process, but I’m sharing this here for now so that people will know why I’m not responding.

Going through this person's timeline shows many public statements constituting incitement to violence and genocide:

![image](https://github.com/NixOS/foundation/assets/13164844/3bceebed-3774-48ca-a356-b0cead357d72)

https://twitter.com/shlevy/status/1710569512771236190

Does "online or offline" include statements made on other online public platforms?

**Comment by shieldfoss** [comment]
That screenshot does not show a tweet that breaks the rules as written. It is not violence. It is not a threat of violence. It is not an incitement of violence. It is not encouragement of self-harm.

What that screenshot *shows* is desperate reach for a fig leaf. A decision to dig into the past only grants credence to claims that the ban was not due to any current behavior, further deligitimizing the process that led to it.

**Comment by cbleslie** [comment]
@shieldfoss, Hi, I think this is my first interaction with you. I hope you're doing okay.

> That screenshot does not show a tweet that breaks the rules as written.

 This is true or false depending on interpenetration of phrase `incitement of violence`. 

***A*** definition of incitement is:

> an act of urging on or spurring on or rousing to action or instigating

This is not my intent to cherry-pick a fitting definition. This is the first definition I found. Most others lined up with this.

With the definition of `incitement` chosen one could categorize the aforementioned tweet as an urging on of genocide. Given the tone I don't think Mr. Levy was musing about the possibility of said violence, I think, at the moment of this tweet, **he wanted this action to happen**. That being said, I am not entirely sure if he still feels this way, now. People are allowed to change and be better. Even if they say incredibly hateful incentive things. 

Regardless of your viewpoint (or mine) in this matter, his ban is at the moderation team's discretion. I think @LGUG2Z just wanted clarity on the rules, perhaps? You deserve that clarity, too!

 I think we have an opportunity!

Moderation team(s),

I think this might be an opportunity for moderation team to clarify, and re-structure this section of the COC and provide greater clarity on:

-  What constitutes incitement
-  @LGUG2Z question, does the COC enforcement include statements made on other online public platforms, Twitter or Facebook for example?
- What constitutes and individual? Can a whole community be an `individual`? 
- Should the COC be expanded to include more than individuals?

I want to follow the rules, and I want moderation team to have their best shot at following them too. I think clarity on this issue might help us all.

Thank you for reading. Sorry about the long post.

**Comment by pbiggar** [comment]
Who does "these savages" refer to? I believe it means Palestinians, since he refers to "feeding them", though it might refer to "people in Gaza". If you don't believe this is violence, perhaps the ["derogatory language"](ttps://github.com/NixOS/foundation/blob/master/governance/zulip/coc.md#derogatory-language
) section is more appropriate, as this refers to national origin, background, race and/or ethnicity, or geographic location.

That said, if your COC allows this language, why have a COC? May as well just pack in it and stop pretending at that point.

**Comment by shieldfoss** [comment]
@pbiggar  - by the CoC, you are required to assume good will. Presumably then: He means "Hamas," who savagely attacked the civilian population of Israel shortly before the Shlevy wrote a tweet calling them savages.

Or you could ask him instead of guessing.

@cbleslie 

> his ban is at the moderation team's discretion

I am aware. And this apparently-unprincipled moderation decision causes me harm, specifically by making me feel anxious (my heart is racing as I write this post) which, according to the new CoC language entitles me to (1) a *sincere* apology from the moderation team and (2) a change in behavior from the moderation team.

How is the moderation team going to sincerely apologize if they believe they did the right thing? Or if, taking my statement into account, they realize their behavior is harmful such they actually can offer a sincere apology for causing me anxiety, how are they going to change if they believe they acted in accordance with the code? Will they just stop following the code? The thought of a CoC that applies to everybody *except* the moderation team makes me *more* worried about the future of the project.

Which was the problem with that language that Shlevy was highlighting (I believe, I have not asked him): It is a fully general license for everybody to require everybody else to change what they are doing, even if they believe they are doing nothing wrong. Nevertheless, given that this *is* the language that was merged in and I *do* feel unsafe in an environment of opaque moderation made on hidden evidence, a plain text reading of the CoC requires the CoC to be reworded until it no longer harms me by inducing anxiety about the projects future governance.

**Comment by AshleyYakeley** [comment]
OP cut it off, but this tweet was dated October 7th.

**Comment by azahi** [comment]
> Does "online or offline" include statements made on other online public platforms?

This is ridiculous, of course it shouldn't matter what statements Shea made outside Zulip, which by the way **is** the scope of this CoC, or other platforms managed by the NixOS community. Frankly, I don't understand why this issue was even created. What are you trying to prove here?

**Comment by shieldfoss** [comment]
@azahi for most any platform, off-platform conduct matters to the platform - in particular for NixOs, consider a participant that changes a decision or statement because another participant threatened them.

The problem arises when the CoC is written such that the moderation team is required to make decisions they are not well-placed to make, and I am incredibly sympathetic to claims that a code of conduct cannot be an exact do-or-don't list because novel situations occur all the time and need to be adjudicated individually.

For the purpose of this exact tweet: A lot can be accomplished here by adopting battle-tested standards from other systems, which is why I do not consider the tweet in question "incitement," - US law would not consider it incitement.

For the purpose of future behavior in accordance with the CoC, one of the ways actual court systems maintain the perception of rule-of-law is that the process is conducted in public, and the evidence that leads to decisions is available to any interested party. Third parties can disagree with the decision but at least they *know the evidence on which the decision was made* and can adjust their understanding of the law accordingly.

This is, of course, only necessary for a system if it values rule-of-law higher than the ability of insiders to make unprincipled decisions for personal satisfaction.

**Comment by shlevy** [comment]
There’s no need to spend time digging up old screenshots, you can just ask what my views are.

Since you brought it up: Yes, I think that the 10/7 attacks revealed (again) that Hamas (and others who participated) are worse than savages and that they deserve obliteration.

I don’t see what possible relevance this has to the Nix foundation, but I’ll leave that to them.

**Comment by thufschmitt** [comment]
I'm locking this as it's not going anywhere. I'll let moderation decide of any further action.
