### ISSUE TITLE
Fix the OpenCollective team members

### ISSUE THREAD

**Issue by zimbatm** [NixOS/foundation#53]
https://opencollective.com/nixos should list Theophane and Ron, and remove Rob.

Depending on how we want to tread the board observers, remove Graham, or add me.

**Comment by thufschmitt** [comment]
This is mostly done, except for 

> Depending on how we want to tread the board observers, remove Graham, or add me.

Do we want to have a policy on this? I'd be in favor of only keeping the board members by default since this is handling the foundation's money and they are the ones who are legally bound to the foundation, but unless we get more observers it's not too big a deal either

**Comment by thufschmitt** [comment]
Actually: The board members are members of the [NixOS](https://opencollective.com/nixos) organization, but this one is mostly a proxy for [nixos_org](https://opencollective.com/nixos_org) which is the actual fiscal host (and is owned by Eelco and Rob). @edolstra can you clarify the relationship between these?

**Comment by edolstra** [comment]
Done.
